<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>FoodDelivery | By Gurinovich</title>
  <link rel="icon" type="image/x-icon" href="/static/main_style/img/favicon.png"/>
  <link rel="stylesheet" href="/static/admin_panel_style/vendors/feather/feather.css">
  <link rel="stylesheet" href="/static/admin_panel_style/vendors/ti-icons/css/themify-icons.css">
  <link rel="stylesheet" href="/static/admin_panel_style/vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="/static/admin_panel_style/style.css">

</head>

<body>
<div class="container-scroller">
  <div class="container-fluid page-body-wrapper full-page-wrapper">
    <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary" style="background-color: #CDDC39 !important;">
      <div class="row flex-grow">
        <div class="col-lg-7 mx-auto text-white">
          <div class="row align-items-center d-flex flex-row">
            <div class="col-lg-6 text-lg-right pr-lg-4">
              <h1 class="display-1 mb-0">${statusCode}</h1>
            </div>
            <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
              <h2>SORRY!</h2>
              <h3 class="font-weight-light">${errorMsg}</h3>
            </div>
          </div>
          <div class="row mt-5">
            <div class="col-12 text-center mt-xl-2">
              <a class="text-white font-weight-medium" href="/">Back to home</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/static/admin_panel_style/vendors/js/vendor.bundle.base.js"></script>
<script src="/static/admin_panel_style/js/off-canvas.js"></script>
<script src="/static/admin_panel_style/js/hoverable-collapse.js"></script>
<script src="/static/admin_panel_style/js/template.js"></script>
<script src="/static/admin_panel_style/js/settings.js"></script>
<script src="/static/admin_panel_style/js/todolist.js"></script>
</body>

</html>
